/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_prog_1(char *host, int x, int y)
{
	CLIENT *clnt;
	float  *result_1;
	numeros  suma_1_arg;
	float  *result_2;
	numeros  resta_1_arg;
	float  *result_3;
	numeros  multiplicacion_1_arg;
	float  *result_4;
	numeros  division_1_arg;


       suma_1_arg.x = x;
       suma_1_arg.y = y;
       resta_1_arg.x = x;
       resta_1_arg.y = y;
       multiplicacion_1_arg.x = x;
       multiplicacion_1_arg.y = y;
       division_1_arg.x = x;
       division_1_arg.y = y;

#ifndef	DEBUG
	clnt = clnt_create (host, calculadora_PROG, calculadora_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
        
        int opcion;
        printf("1.suma\n");
        printf("2.resta\n");
        printf("3.multiplicacion\n");
        printf("4.division\n");
        printf("Selecione una opcion: ");
        scanf("%d",&opcion);
        
        switch(opcion){
          case 1:
         result_1 = suma_1(&suma_1_arg, clnt);
	 if (result_1 == (float *) NULL) {
	     clnt_perror (clnt, "call failed");
	  }
         printf("resultado = %f\n:",*result_1); 
          break;
          case 2:
         result_2 = resta_1(&resta_1_arg, clnt);
	 if (result_2 == (float *) NULL) {
	    clnt_perror (clnt, "call failed");
	  }
           printf("resultado = %f\n:",*result_2); 
          break;
          case 3:
         result_3 = multiplicacion_1(&multiplicacion_1_arg, clnt);
	 if (result_3 == (float *) NULL) {
	    clnt_perror (clnt, "call failed");
          }
           printf("resultado = %f\n:",*result_3); 
          break;
          case 4:
         result_4 = division_1(&division_1_arg, clnt);
	if (result_4 == (float *) NULL) {
	  clnt_perror (clnt, "call failed");
	}
          printf("resultado = %f\n:",*result_4); 
          break;
        }
       


#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
        int x, y;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
        x = atof(argv[2]); //atof() convierte una cadena a su valor numerico
        y = atof(argv[3]);
	calculadora_prog_1 (host,x,y);
exit (0);
}
